version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT"

  mesos-master:
    image: mesosphere/mesos-master:1.5.2
    container_name: mesos-master
    privileged: true
    environment:
      - MESOS_HOSTNAME=$HOST_IP
      - MESOS_CLUSTER=SMACK
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
    depends_on:
      - zookeeper
    ports:
      - "5050:5050"
    healthcheck:
      test: "curl -f http://localhost:5050/health || exit 1"

  mesos-slave:
    image: mesosphere/mesos-slave:1.5.2
    container_name: mesos-slave
    pid: "host"
    privileged: true
    environment:
      - MESOS_HOSTNAME=$HOST_IP
      - MESOS_PORT=5151
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_SYSTEMD_ENABLE_SUPPORT=false
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    depends_on:
      - zookeeper
      - mesos-master
    ports:
      - "5151:5151"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  chronos:
    image: mesosphere/chronos:v3.0.2
    container_name: chronos
    command: '--zk_hosts zookeeper:2181 --master zk://zookeeper:2181/mesos'
    environment:
      PORT0: 4400
      PORT1: 8080
    ports:
      - "4400:4400"
    depends_on:
      - zookeeper
      - mesos-master
    healthcheck:
      test: "curl -f http://localhost:4400 || exit 1"
